cluster_name = "jupyter-docker-terraform-qiuyangz"
master_instance_type="n1-standard-2"
worker_instance_type="n1-standard-2"
project_id = "amazing-autumn-398923"
bucket_name="amazing-autumn-398923-hw5-new-bucket"
region="us-central1"
zone="us-central1-a"